version: '3.3'

services:
      
  bb-db:
    image: ${dockerId}/bulletin-board-db
    build:
      context: ./bulletin-board-db
    networks:
      - bb-net

  bb-app:
    image: ${dockerId}/bulletin-board-app
    build:
      context: ./bulletin-board-app
    ports:
      - "8080:8080"
    depends_on:
      - bb-db
    restart: on-failure
    networks:
      - bb-net

networks:
  bb-net: